### ISSUE TITLE
Bad solutions for exercise one [Two sum]

### ISSUE THREAD

**Issue by sonirico** [halfrost/LeetCode-Go#1]
你好,

I noticed that solutions (for both tests and implementation)  for exercise one ([Two sum](https://github.com/halfrost/LeetCode-Go/tree/master/Algorithms/0001.%20Two%20Sum)) correspond to exercise two ([Add two numbers](https://github.com/halfrost/LeetCode-Go/tree/master/Algorithms/0002.%20Add-Two-Number)).

I could make a PR uploading the actual examples for _Two sum_, but it feels like it's been done already but lost somewhere.

**Comment by halfrost** [comment]
ops, it's my mistake. Thank you very much for pointing this problem out. I have fixed it. Thx~
