### ISSUE TITLE
请问有些代码中用到的数据结构如listnode是怎么导入的

### ISSUE THREAD

**Issue by birdmanmandbir** [halfrost/LeetCode-Go#10]

**Comment by halfrost** [comment]
只要把这个结构体的定义写在一个包内就可以了。。我是写在第 206 题里面了，由于都在一个包里面，所以其他题可以直接用。

**Comment by birdmanmandbir** [comment]
> 只要把这个结构体的定义写在一个包内就可以了。。我是写在第 206 题里面了，由于都在一个包里面，所以其他题可以直接用。

这样嘛？可是虽然包相同，但每道题有自己的文件夹，这种情况go应该不会认为是同一个包？
我在goland上就无法自动识别出listnode的位置

**Comment by halfrost** [comment]
> > 只要把这个结构体的定义写在一个包内就可以了。。我是写在第 206 题里面了，由于都在一个包里面，所以其他题可以直接用。
> 
> 这样嘛？可是虽然包相同，但每道题有自己的文件夹，这种情况go应该不会认为是同一个包？
> 我在goland上就无法自动识别出listnode的位置

奇怪了，我是用 VSCode，这样是可以的。有时间我研究一下 goland，看是不是有特殊处理。

**Comment by halfrost** [comment]
@birdmanmandbir 我都改好了，我把那些固定的数据结构放在一个包里面了，你重新拉一下 master。

**Comment by yiliyili** [comment]
> @birdmanmandbir 我都改好了，我把那些固定的数据结构放在一个包里面了，你重新拉一下 master。
我刚拉了代码,第2题跑不通
PS C:\project> go install github.com/halfrost/LeetCode-Go/structures
can't load package: package github.com/halfrost/LeetCode-Go/structures: cannot find package "github.com/halfrost/LeetCode-Go/structures" in any of:
        C:\Go\src\github.com\halfrost\LeetCode-Go\structures (from $GOROOT)
        C:\project\src\github.com\halfrost\LeetCode-Go\structures (from $GOPATH)

github.com/halfrost/LeetCode-Go/structures这个包载入不进来

**Comment by halfrost** [comment]
@yiliyili go get "github.com/halfrost/LeetCode-Go" ，这一步执行成功了不？

**Comment by yiliyili** [comment]
> @yiliyili go get "github.com/halfrost/LeetCode-Go" ，这一步执行成功了不？

![image](https://user-images.githubusercontent.com/10955208/89657258-5f93c000-d8ff-11ea-9b14-aa8135c6b807.png)

我明白了,这个项目的安装方式是有要求的,比如go get "github.com/halfrost/LeetCode-Go"    而我安装是fork了之后拉取到一个我常用的C:\project\src目录下,因为github.com我存放的是第三方包,把题解放在这里觉得怪怪的,而且也没有在github.com这个目录下建立版本库

**Comment by yiliyili** [comment]
![image](https://user-images.githubusercontent.com/10955208/89657642-f6607c80-d8ff-11ea-8449-c8c476ec7496.png)
![image](https://user-images.githubusercontent.com/10955208/89658629-5c013880-d901-11ea-8a4b-a6d7b8c2c0f2.png)
我测试了确实是项目对安装位置有要求git pull到其他的目录下,第二题就不能成功

**Comment by yiliyili** [comment]
目前要正确运行的话,似乎只有通过go get "github.com/halfrost/LeetCode-Go" 的方式下载项目,git pull本项目到任意目录是不可行的

**Comment by halfrost** [comment]
@yiliyili 嗯，你可以理解你把这个 repo 当成了一个 package 安装到你本地的 gopath 中了。看截图你本地应该成功了。暂时没其他的问题了吧？

**Comment by yiliyili** [comment]
没问题了,安装方式可能需要在readme中说明一下,不然可能有人像我一样git pull自定义安装目录,

**Comment by halfrost** [comment]
好的~👌
