### ISSUE TITLE
924 题 好像有一个condition 忘记检查了。

### ISSUE THREAD

**Issue by xiaomingLu036** [halfrost/LeetCode-Go#106]
我们除了找节点在的最大的集合之外，还要确保这个集合只有一个感染源， 如果这个最大的集合有多个感染源那么移除掉一个并不会造成任何不同。

**Comment by xiaomingLu036** [comment]
当然 也可能是我看漏了， 没有实际的跑一次因为你用了自己的tempLate.

**Comment by halfrost** [comment]
@xiaomingLu036 您好，我验证了一下你的说法，我确实漏掉了这种情况。但是你说的这种情况应该是后来新增的测试用例。我在 2019 年做这道题的时候，AC 了。这是我当时的 AC 后台记录：https://leetcode.com/submissions/detail/252345417/

我再修改一下。🙏🏻

**Comment by halfrost** [comment]
@xiaomingLu036 您好，代码我已经修复了，目前已经 AC 了。再次感谢你指出错误。

**Comment by xiaomingLu036** [comment]
没事，也谢谢你给的总结，知道有些人也一直在刷题，给自己不少动力 :)

**Comment by halfrost** [comment]
哈哈，刷题的路上一起共勉咯💪🏻
