### ISSUE TITLE
为啥单元测试用例没有使用断言？

### ISSUE THREAD

**Issue by NovaHe** [halfrost/LeetCode-Go#108]
如题，使用断言方式更加像一个项目

**Comment by halfrost** [comment]
@NovaHe 您好，先谢谢大佬指出这个问题。这 repo 我是 2017 年那会新建的，当时我还是 Go 新手，公司项目中也没有写 test 文件。后来到了 2019 年公司新项目里面 test 都用了断言。但是我累积了 2 年的题量就没有回头去加上断言了。直到现在这个 repo 突然 “火”了，知道的人多了，所以 test 没有加上断言的问题就“暴露”出来了。我在考虑写一个脚本，把目前这几百套题的 test 自动加上断言。😂

**Comment by NovaHe** [comment]
感谢回复@halfrost ，高代码质量，可以更多star吧
