### ISSUE TITLE
能不能实现一个刷题记录器

### ISSUE THREAD

**Issue by gaojiankang** [halfrost/LeetCode-Go#154]
如题能不能实现一个刷题记录器，如果已经做过就打勾，不用登录使用cookie存到浏览器就行，这样就不用对着目录找哪个刷过哪个没刷过了

**Comment by halfrost** [comment]
@gaojiankang 你这个需求并不难。在 ctl 里面我实现了类似的功能。先拿到自己的 token，请求自己账号下做了哪些题，然后把这些题号写入到文件中。至于你还想显示打钩在网页上，需要写一个 chrome 插件，修改 DOM。刷题记录器应该有人写过了，你网上可以找找看。VSCode 的上 LeetCode 插件也有类似的功能。
