### ISSUE TITLE
A problem in 707. Design Linked List 

### ISSUE THREAD

**Issue by Shiwei-Luo** [halfrost/LeetCode-Go#215]
```go
func (this *MyLinkedList) DeleteAtIndex(index int) {
	cur := this
	for i := 0; cur != nil; i++ {
		if i == index-1 {
			break
		}
		cur = cur.Next
	}
	if cur != nil && cur.Next != nil {
		cur.Next = cur.Next.Next
	}
}
```
It seems that the case that index equals 0 is not taken into account.

**Comment by halfrost** [comment]
> ```go
> func (this *MyLinkedList) DeleteAtIndex(index int) {
> 	cur := this
> 	for i := 0; cur != nil; i++ {
> 		if i == index-1 {
> 			break
> 		}
> 		cur = cur.Next
> 	}
> 	if cur != nil && cur.Next != nil {
> 		cur.Next = cur.Next.Next
> 	}
> }
> ```
> 
> It seems that the case that index equals 0 is not taken into account.

@Shiwei-Luo You are right. I have fixed this bug. Please pull the latest code.
