### ISSUE TITLE
763 PartitionLabels 时间复杂度

### ISSUE THREAD

**Issue by 0xff-dev** [halfrost/LeetCode-Go#236]
您好，昨天做到了这道题，然后和您这边的解法做了一个对比，都是lastIndex的逻辑。readme中写了复杂度是`O(n^2)`，但解法1的start更新为end+1，我觉得时间复杂度是`O(n)`的。

**Comment by halfrost** [comment]
@0xff-dev 你说的是对的，我这里写错了。感谢指出，我已经更正了。
