### ISSUE TITLE
关于此电子书如何搭建

### ISSUE THREAD

**Issue by poshoi** [halfrost/LeetCode-Go#241]
编程小白，请问类似于这种的电子书是怎么编写搭建的，之前听说过gitbook，但是能不能像做笔记一样私有化部署起来，家中有NAS，想用docker之类的部署一个。
谢谢。

**Comment by poshoi** [comment]
谢谢大佬！！！！
我去试一下

**Comment by poshoi** [comment]
@halfrost 搭建了一晚上，HUGO后台登陆好像可以，但是主题弄半天弄不上，DOCKER中git用不了，我又尝试原始方法，把主题解压放到相应文件，同时复制新的config.toml，这会导致docker应用打不开，报错是key不对。搞的我现在头疼。

**Comment by halfrost** [comment]
@poshoi 把 key 不对的错误修复一下。把主题解压到这个文件中，这种做法应该很稳才对。

**Comment by poshoi** [comment]
可能docker版本有点小问题吧，我刚看日志，有个SCSS文件与我这个HOGO版本不适配，需要用扩展的版本，好麻烦
