### ISSUE TITLE
Windows系统下 关于 Clone 的问题

### ISSUE THREAD

**Issue by StellarisW** [halfrost/LeetCode-Go#242]
[https://github.com/halfrost/LeetCode-Go/tree/master/leetcode/1576.Replace-All-s-to-Avoid-Consecutive-Repeating-Characters](url)
Leecode 1576 题目的文件夹和里面的文件的名字都包含了字符'?'
导致windows系统不能克隆文件到本地
`
remote: Enumerating objects: 19163, done.        
remote: Counting objects: 100% (59/59), done.        
remote: Compressing objects: 100% (21/21), done.        
remote: Total 19163 (delta 40), reused 47 (delta 38), pack-reused 19104        
Receiving objects: 100% (19163/19163), 18.26 MiB | 817.00 KiB/s, done.
Resolving deltas: 100% (12199/12199), done.
error: invalid path 'leetcode/1576.Replace-All-s-to-Avoid-Consecutive-Repeating-Characters/1576. Replace All ?'s to Avoid Consecutive Repeating Characters.go'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`

**Comment by haowan1015** [comment]
呵呵，来信收到，谢谢

**Comment by xiaokuer** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by halfrost** [comment]
> [https://github.com/halfrost/LeetCode-Go/tree/master/leetcode/1576.Replace-All-s-to-Avoid-Consecutive-Repeating-Characters](url) Leecode 1576 题目的文件夹和里面的文件的名字都包含了字符'?' 导致windows系统不能克隆文件到本地 `remote: Enumerating objects: 19163, done. remote: Counting objects: 100% (59/59), done. remote: Compressing objects: 100% (21/21), done. remote: Total 19163 (delta 40), reused 47 (delta 38), pack-reused 19104 Receiving objects: 100% (19163/19163), 18.26 MiB | 817.00 KiB/s, done. Resolving deltas: 100% (12199/12199), done. error: invalid path 'leetcode/1576.Replace-All-s-to-Avoid-Consecutive-Repeating-Characters/1576. Replace All ?'s to Avoid Consecutive Repeating Characters.go' fatal: unable to checkout working tree warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'`

@StellarisW 收到了，我找个时间把这个问题修复一下。我会把文件名里面的特殊符号(？<> )都去除掉。

**Comment by StellarisW** [comment]
还是会出现这样的问题，只改文件夹名还不行，还要改里面的文件名

**Comment by halfrost** [comment]
> 还是会出现这样的问题，只改文件夹名还不行，还要改里面的文件名

再试试，刚刚合并了你的那个 pr，我看你更改了里面的文件名。现在可以 clone 了么？

**Comment by StellarisW** [comment]
问题解决了
