### ISSUE TITLE
Query: What is the technology behind web ? thank you

### ISSUE THREAD

**Issue by iswanulumam** [halfrost/LeetCode-Go#259]
What is the technology / tools to create website https://books.halfrost.com/leetcode/ ?

**Comment by halfrost** [comment]
I use the Hugo framework to build this website. Hugo is one of the most popular open-source static site generators, which bases on golang.

**Comment by iswanulumam** [comment]
Thanks

**Comment by bohrasankalp** [comment]
'hugo server -D' commands end with serving file but the url is being served without url scheme that fail to run server. Any config changes required?

**Comment by halfrost** [comment]
> 'hugo server -D' commands end with serving file but the url is being served without url scheme that fail to run server. Any config changes required?

@bohrasankalp "without url scheme" means without https? Can you paste some detail of error log for me?

**Comment by bohrasankalp** [comment]
Thats done. @halfrost
