### ISSUE TITLE
1004 Max Consecutive Ones III

### ISSUE THREAD

**Issue by PangZhiww** [halfrost/LeetCode-Go#270]
1004题代码
https://github.com/halfrost/LeetCode-Go/blob/master/website/content/ChapterFour/1000~1099/1004.Max-Consecutive-Ones-III.md
网页版缺少max函数 thank you

**Comment by haowan1015** [comment]
呵呵，来信收到，谢谢

**Comment by xiaokuer** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by halfrost** [comment]
已添加。
