### ISSUE TITLE
网站证书过期，无法访问

### ISSUE THREAD

**Issue by huberyhe** [halfrost/LeetCode-Go#282]
https://books.halfrost.com 证书过期了

**Comment by halfrost** [comment]
@huberyhe 更新好了，麻烦你刷新一下。So sorry about that. （我的自动刷新证书的 bot 居然没有帮我自动更新。过去几年都问题，我晚点查一查 log）

**Comment by huberyhe** [comment]
> @huberyhe 更新好了，麻烦你刷新一下。So sorry about that. （我的自动刷新证书的 bot 居然没有帮我自动更新。过去几年都问题，我晚点查一查 log）

可以了，多谢
