### ISSUE TITLE
是否增加 python solutions？

### ISSUE THREAD

**Issue by lyricslee** [halfrost/LeetCode-Go#65]
目前 leetcode 下都是 go 写的 solutions，是否考虑增加 python 版本的 solutions 呢？因为大量的同学不会 golang。

**Comment by halfrost** [comment]
> 目前 leetcode 下都是 go 写的 solutions，是否考虑增加 python 版本的 solutions 呢？因为大量的同学不会 golang。

您好，python 版本的 solutions 如果有人提 PR，我会加在目录中。我的 python 水平一般，就不献丑啦。其实精通 C 系列的语言的话，学习 golang 很快的，就 25 个关键字，可能看 2 个小时语法就可以了。
