### ISSUE TITLE
287 题二分查找的解析与代码不一致，解析存在问题

### ISSUE THREAD

**Issue by imageslr** [halfrost/LeetCode-Go#7]
## 简述
实测发现，按照题解写出来的代码会陷入死循环。对比了实际代码，发现题解和代码在细节上不一致。题解的思路是正确的，但是细节描述有问题。

题解说：
> 1 和 7 的中位数是 4，遍历整个数组，统计**小于** 4 的整数的个数，至多为 3 个，如果超过 3 个就说明重复的数存在于区间 **[1,4)** 中；否则，重复的数存在于区间 **[4,7]** 中。

加粗的两个位置成立的前提是**计算中位数的时候必须向上取整**。但是编程语言的除法是**向下取整**的。所以如果 low 和 high 相邻，那么 mid 将一直等于 low，然后会一直在区间 `[mid, high]` 死循环。

## 正解
1. 假设有 n+1 个数，则可能重复的数位于区间 `[1, n]` 中。记该区间最小值、最大值和中间值为 low、high、mid
2. 遍历整个数组，统计**小于等于** mid 的整数的个数，至多为 mid 个
3. 如果超过 mid 个就说明重复的数存在于区间 `[low,mid]` （**闭区间**）中；否则，重复的数存在于区间 `(mid, high]` （**左开右闭**）中
4. 缩小区间，继续重复步骤 2、3，直到区间变成 1 个整数，即 low == high
5. 整数 low 就是要找的重复的数

`代码在本仓库 287 题的源文件里。`
```go
func findDuplicate(nums []int) int {
	low, high := 1, len(nums)-1
	for low < high {
		mid, count := (low+high)/2, 0
		for _, num := range nums {
			if num <= mid {
				count++
			}
		}
		if count > mid {
			high = mid
		} else {
			low = mid + 1
		}
	}
	return low
}
```

## 错解改正
**注意**，一种错误的做法是：
1. 遍历整个数组，统计**小于** mid 的整数的个数，至多为 mid-1 个
2. 如果超过 mid-1 个就说明重复的数存在于区间 `[low,mid)` （**左闭右开**）中；否则，重复的数存在于区间 `[mid, high]`（**闭区间**） 中

错误原因在于，编程语言的除法是向下取整的。如果 low 和 high 相邻，那么 mid 将一直等于 low，将一直在区间 `[mid, high]` 死循环。因此必须保证下一次遍历时，mid 不等于上一轮的 mid。上面的正确做法就有这个保证，这里如果**把求 mid 的除法运算改成向上取整**，就可以通过了。
```go
		mid, count := (low+high+1)/2, 0 // ①
		for _, num := range nums {
			if num < mid { // ②
				count++
			}
		}
		if count >= mid { // ③
			high = mid - 1
		} else {
			low = mid // ④
		}
```

**Comment by halfrost** [comment]
👍🏻 你说的是对的。按照我说的那样向下取整就会死循环了。你解释的非常清楚！我改了题解，尊重你的描述，我按照你的解答改正啦~ 我也注明了感谢你的指正 👏🏻

(回复你晚了哈，今天把所有邮件都清理了一下发现了这个 issue 了。之前 1 月忙了一些个人的“人生大事”，紧接着过年闹肺炎，忙着一直都没缓过来)
