### ISSUE TITLE
86题答案好像不太对

### ISSUE THREAD

**Issue by reaperhero** [halfrost/LeetCode-Go#73]
func Test_partition(t *testing.T) {
	input1, input2 := structures.Ints2List([]int{1, 4, 3, 2, 5, 2}), 3
	fmt.Println(structures.List2Ints(partition(input1,input2))) // [1 2 2 4 3 5]
}

4不是应该在3后面么

**Comment by halfrost** [comment]
@reaperhero 这一题的答案没有错误哈，这一题只要求了 partition，并没有要求 partition 之后保证有序。即所有小于 x 的节点排在大于或等于 x 的节点之前，但是大于等于 x 的节点相互之间不需要有序~

**Comment by reaperhero** [comment]
好的，感谢指导
