### ISSUE TITLE
请问PWA版本在哪里？怎么使用？

### ISSUE THREAD

**Issue by karlzheng** [halfrost/LeetCode-Go#77]
请问PWA版本在哪里？怎么使用？谢谢！

**Comment by halfrost** [comment]
@karlzheng 您好，PWA 的使用方法如下：

电脑端的话，以 Chrome 为例，用 Chrome 访问在线的阅读页面，点击地址栏最后面的那个小加号，即可安装。总共大小不到 800K。

<img width="705" alt="截屏2020-10-13 下午6 18 03" src="https://user-images.githubusercontent.com/10825609/95848439-a4fdbf00-0d80-11eb-90ce-013100022c18.png">

手机端的话，以 iOS 为例，Android 类似的。用 Safari 访问在线的阅读页面，点击添加到主屏幕，即完成了 PWA 的安装。

![IMG_4258](https://user-images.githubusercontent.com/10825609/95848580-d080a980-0d80-11eb-8cf7-a4c31906cb0c.jpg)
