### ISSUE TITLE
问一个关于746. Min Cost Climbing Stairs的问题

### ISSUE THREAD

**Issue by vivozhitao** [halfrost/LeetCode-Go#78]
首先感谢halfrost以及大家的贡献。我在看746题的过程中，觉得第一个example的答案应该是10吧？就是我可以先从index=0开始，然后付费后，选择走两步阶梯到达顶端，不知道我的理解哪里有错？谢谢。

**Comment by halfrost** [comment]
(哎呀，第 746 题的评论忘记初始化了，现在初始化完成了)

题目的意思是说你站在哪个楼层，先支付 cost，然后你才能开始继续走。第一个 example，你站在 0 层，先支付 10，开始走 2 步，你就到了第
2 层，这个时候还不是顶层，你还需要支付 20 ，才能到顶层，所以这样的策略走的话，是 30 。而不是 10 。

ZX <notifications@github.com> 于2020年10月26日周一 上午5:56写道：

**Comment by vivozhitao** [comment]
但是题目中的原话是：Once you pay the cost, you can either climb one or two steps。意思就是，如果我站在0层，先支付了10，那就可以选择climb two steps，于是就到了顶层？

**Comment by halfrost** [comment]
> 但是题目中的原话是：Once you pay the cost, you can either climb one or two steps。意思就是，如果我站在0层，先支付了10，那就可以选择climb two steps，于是就到了顶层？

@vivozhitao 站在0层，先支付了10，爬 2 步以后，到达的是第 2 层，并非顶层。数组下标 2 的位置还有一个 cost，说明往上爬到顶层还需要再花费 20 。你应该是对顶层的这个理解出错了。数组最后一个元素并不是顶层，还需要再往上爬。

**Comment by vivozhitao** [comment]
> 
> 
> > 但是题目中的原话是：Once you pay the cost, you can either climb one or two steps。意思就是，如果我站在0层，先支付了10，那就可以选择climb two steps，于是就到了顶层？
> 
> @vivozhitao 站在0层，先支付了10，爬 2 步以后，到达的是第 2 层，并非顶层。数组下标 2 的位置还有一个 cost，说明往上爬到顶层还需要再花费 20 。你应该是对顶层的这个理解出错了。数组最后一个元素并不是顶层，还需要再往上爬。

哦，原来如此！多谢！这个真是很容易误解~~~

**Comment by halfrost** [comment]
@vivozhitao 我当时针对第一个 example 也考虑了一下。和你想的一样，但是我看到数组里面下标 2 的地方还有值，我就明白，到了 2 楼以后，还不是顶楼，因为还有 cost 需要支付。所以题目中的顶楼是比数组里面元素多 1 的。到了顶楼，自然不需要 cost 了，所以顶楼也就不在数组里面了。我就按照我这个想法尝试了写了一版，就 AC 了。也验证了题目就是这个意思 😉

**Comment by vivozhitao** [comment]
@halfrost 所以如果现场做这个题，我估计就GG了。。。理解都需要时间。
