### ISSUE TITLE
API rate limit exceeded，太火了。。。

### ISSUE THREAD

**Issue by Ahacad** [halfrost/LeetCode-Go#80]
```
Error: API rate limit exceeded for app ID 75d9d747f200c623a0e6..
```

**Comment by halfrost** [comment]
🙏🏻 感谢各位大佬的关注，最近各个公众号也有人发现这个项目，他们有发链接。昨晚我更新了周赛的题解，被人转发到了某刷题大群了。所以瞬间访问的人数多，被 Github 限流了。不过查了一下，这个错误很快就能恢复。现在已经恢复了。

再次感谢各位大佬们的关注。近期涨 Star 比较猛，眼看着从 8.7 K 一下子就涨到 9.3 K 了。元旦之前很可能就要破 10 K 了。谢谢大家的关注，我继续好好努力的更新题解~💪🏻
