### ISSUE TITLE
复用网站工程和hugo theme.

### ISSUE THREAD

**Issue by dongzl** [halfrost/LeetCode-Go#81]
作者你好，最近也在用leetcode刷题，我是java开发，想把自己刷题的一些思路也记录一下，看到你这个网站包括主题都非常棒，想直接复用一下，题解用java实现，记录自己的学习过程，复用网站工程和 hugo theme，不知是否同意，谢谢！

**Comment by halfrost** [comment]
@dongzl 您好，可以的。我的这个 hugo theme 也是基于开源的 hugo-book theme 主题修改而来的。我增加了 Dark 模式，增加了 Gitalk，增加了访问统计，增加了 Prism 代码高亮……等等一些我要用的功能。目前主题方面我觉得还欠缺的是，前一页和下一页功能，这个我是用 MarkDown 自己实现的。还有一个就是目录页可折叠功能，因为题目一多以后，目录全部展开变得很长，找题目只能用搜索框搜索题号。这两个功能已经提了 issue 给原主题的开发者了。我有空也会实现一下这 2 个功能。

祝你刷题顺利，可以经常相互交流最优解法~🙏🏻

**Comment by dongzl** [comment]
@halfrost ,感谢您的辛苦付出和无私贡献，的确您修改后的theme比原来有很大增强，建议如果可以，也 merge 回 hugo-book 工程中，这样能让更多人享受到这些新功能。

我刚刷题时间不长，才 100+，有些刷过就忘，leetcode 网站复习做过题目不是很方便，所以也想像您学习整理一下。

我整理题目目前的想法是发掘某个题目的多种不同解法，这样感觉更能开阔自己一些编程思路，我看您的题解都是追求极致最优，非常赞呢，有机会我们一起交流~

**Comment by halfrost** [comment]
@dongzl 嗯，我会争取 merge 到原主题里面去。有些地方的改法和原主题的主人理念有些不同。例如目录折叠功能，其实用 JS 很容易就能完成。但是原主题的主人的理念是不想引入任何 JS 文件，这个功能他只想用纯 CSS 的方式解决。确实也可以实现，有思路，但是做起来好像很麻烦。至少我没有搞定。用纯 CSS 的方式代替 JS，还是有难度。所以这些地方的实现如果不符合原主题主人的理念，就不能被合并进去。

一道题的多种解法，对思维训练能力是很好的。我之所以追求到极致最优，是因为面试的时候总有面试官问我，“能不能再优化一下？”，“还有没有最优解？”，倒是没有问过我，有没有其他解法。所以我站在面试角度，就要求追求极致最优了。在追求最优的路上，也是思维深度挖掘，进化的过程。所以我觉得，不管是像我这样追求最优解，还是像你这样追求多解，都是训练思维能力的方式。👍🏻

一起加油，与君共勉~💪

**Comment by dongzl** [comment]
嗯嗯，原来是这个原因，我是纯java服务端，前端很弱，所以只能默默给你的贡献点赞~

我准备的不充分，面试的不多，有遇到面试官要多种解法的，当然有可能也是给出的不是最优解，面试官要再发掘一下；具体的过程有时候也是看面试官个人喜好，不过我们积累刷题过程，无论在面试还是工作，都会有很大帮助，另外面试中没有 IDE，纯记事本，对常用 API 也需要刻意去记忆，的确会让自己进步不小~

咱们一起加油~ 💪💪💪
