### ISSUE TITLE
目录包含空格,作者是如何进行测试的?

### ISSUE THREAD

**Issue by yiliyili** [halfrost/LeetCode-Go#9]
import path contains space character: "LeetCode-Go/Algorithms/0001. Two Sum"

**Comment by halfrost** [comment]
我用的 VSCode IDE，上面可以支持空格。。看来不同的 IDE 对 go 原生的命令有封装，那你说的这个问题我研究一下~

**Comment by halfrost** [comment]
@yiliyili 我把所有文件名中的空格都去掉了，也加上了 travis-ci build。舒服。大佬你重新拉取一下 master 吧。

**Comment by yiliyili** [comment]
> @yiliyili 我把所有文件名中的空格都去掉了，也加上了 travis-ci build。舒服。大佬你重新拉取一下 master 吧。

readme.md有冲突,我删除fork,再重新fork后,本地go test第一题1. Two Sum.go ,win下即使文件名有空格也可以跑,看来是文件夹不能有空格,文件名允许有

**Comment by halfrost** [comment]
@yiliyili 那目前还有其他问题不？我本地测试是可以。还有啥问题你说，我修改，保证服务到位。

**Comment by halfrost** [comment]
@yiliyili 对了。我把题解也部署成网站了。方便复习。网站在这里 https://books.halfrost.com/leetcode/。题解在第四章。目前这本书还是预览版哈，还没有完全写完，提前给你预览一下。嘻嘻。。
