### ISSUE TITLE
前来膜拜一下大佬

### ISSUE THREAD

**Issue by Sunyihao** [halfrost/LeetCode-Go#99]
最近也正在每做一个题整理自己的思路，方便以后放到自己的博客上，特地来找大佬取经学习

**Comment by halfrost** [comment]
@Sunyihao 您好呀。欢迎随时留言一起交流。

以后你可以来对应的题目下方留言，这样讨论的过程可以被沉淀下来。有些讨论的过程我觉得对后人来说有价值。这个书的 web 版在这里，https://books.halfrost.com/leetcode/，可以随时来留言。

P.S：前几天评论插件 Gitalk 出了一点问题，它用到了一个跨域的网站被封了。我现在修复好了，又可以欢快的留言了。
> PSA: Public demo server (cors-anywhere.herokuapp.com) will be very limited by January 2021, 31st
